# Use Nginx as base image
FROM nginx:latest

# Copy HTML file to Nginx html folder
COPY index.html /usr/share/nginx/html/index.html

# Expose frontend port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
